# Color Predictor Training Configuration

# Data
buffer_path: "/Users/filippogombac/Documents/GitHub/I-have-a-dreamer/data/replay_buffer_factorized.pkl"  # Path to replay buffer file (use dummy data if not found)

# State Encoder
encoder_type: "vit"  # Options: "mlp", "cnn", "vit"
latent_dim: 256
encoder_params:
  mlp:
    num_hidden_layers: 2
    hidden_dim: 256
    activation_fn_str: "relu"
    dropout_rate: 0.1
    input_channels: 1
    image_size: [10, 10]
  cnn:
    num_conv_layers: 3
    base_filters: 32
    kernel_size: 3
    stride: 2
    padding: 1
    activation_fn_str: "relu"
    fc_hidden_dim: null
    dropout_rate: 0.2
    input_channels: 1
    image_size: [10, 10]
  vit:
    depth: 6
    heads: 4
    mlp_dim: 512
    pool: "cls"
    dropout: 0.1
    emb_dropout: 0.1
    patch_size: 1
    input_channels: 1
    image_size: [10, 10]

# Color Selection Functions
num_color_selection_fns: 19  # Set this to the number of color selection functions in DSL

# Color Predictor
color_predictor_hidden_dim: 128
num_arc_colors: 9

# Training
batch_size: 32
num_epochs: 10
learning_rate: 0.001
num_workers: 1
log_interval: 10 