buffer_path: data/buffer_100.pt
latent_dim: 54
batch_size: 64
num_epochs: 150
learning_rate: 0.0004
num_workers: 0
log_interval: 10
num_color_selection_fns: 4
num_selection_fns: 17
num_transform_actions: 10

encoder_params:
  image_size: [10, 10]
  input_channels: 1
  depth: 3
  heads: 16
  mlp_dim: 512
  transformer_dim: 64
  dropout: 0.2
  emb_dropout: 0.2
  scaled_position_embeddings: false
  colors_vocab_size: 12

decoder_params:
  depth: 5
  heads: 16
  mlp_dim: 512
  transformer_dim: 128
  dropout: 0.2
  colors_vocab_size: 12
