buffer_path: data/buffer.h5
latent_dim: 128
batch_size: 32
num_epochs: 500
learning_rate: 0.0004
num_workers: 0
log_interval: 10
num_color_selection_fns: 4
num_selection_fns: 17
num_transform_actions: 10

encoder_params:
  image_size: [10, 10]
  input_channels: 1
  depth: 2
  heads: 8
  mlp_dim: 512
  transformer_dim: 64
  dropout: 0.2
  emb_dropout: 0.2
  scaled_position_embeddings: false
  colors_vocab_size: 11

decoder_params:
  depth: 2
  heads: 8
  mlp_dim: 512
  transformer_dim: 64
  dropout: 0.2
  colors_vocab_size: 11
